### ISSUE TITLE
Repair dvb.route

### ISSUE THREAD

**Issue by JuRolf** [kiliankoe/dvbpy#15] opened 2019-02-10 22:15 UTC
Hey 
I've seen that you notice that the route is not working anymore. Do you want to fix this bug? I want to work with this module and every time I used it I get a TimeoutError.

Kind regards
JuRolf

**Comment by kiliankoe** [comment] 2019-02-11 15:38
There was some work done for #14 to migrate to using a different API. I don't recall how far I got with that however, but there were definitely some open todos. You're welcome to try it out and see if it works for your use-case, but I unfortunately can't commit to any specific timeframe when that will be finished, sorry.

**Comment by kiliankoe** [comment] 2019-02-11 15:39
I'm going to close this as a dupe of that issue for now.

**Closed by kiliankoe** 2019-02-11 15:39 UTC
Labels: duplicate
